config/routes.rb
Basaglia::Application.routes.draw do
  root to: "pages#show", id: "trainings"
  post "feedback/send", to: "pages#send_feedback", as: :send_feedback
  get ":id", to: "pages#show", as: :page, format: false
end

app/models/feedback.rb
# encoding: utf-8

class Feedback < MailForm::Base
  attribute :message
  attribute :name
  attribute :phone_or_email

  def headers
    {
      subject: "Новое сообщение с сайта",
      to: "olvitacompani@gmail.com",
      from: "olvitacompani@gmail.com"
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  VALID_CHARACTERS = "a-zA-Z0-9~!@$%^&*()#`_+-=<>\"{}|[];',?".freeze

  rescue_from ActionView::MissingTemplate do |exception|
    if exception.message =~ %r{Missing template #{content_path}}
      raise ActionController::RoutingError, "No such page: #{params[:id]}"
    else
      raise exception
    end
  end

  def show
    render template: current_page
  end

  def send_feedback
    @feedback = Feedback.new(
      name: params[:feedback][:name],
      phone_or_email: params[:feedback][:phone_or_email],
      message: params[:feedback][:message]
    )

    @feedback.deliver
    redirect_to root_url
  end

  protected

    def current_page
      "#{content_path}#{clean_path}"
    end

    def clean_path
      path = Pathname.new("/#{clean_id}")
      path.cleanpath.to_s[1..-1]
    end

    def content_path
      "pages/"
    end

    def clean_id
      params[:id].tr("^#{VALID_CHARACTERS}", '')
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for :title do
      page_title
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= [controller_name, action_name].join(" ") %>">
  <div class="container">
    <header class="header">
      <nav class="pages">
        <ul>
          <% %w(trainings publications contact-us feedback).each do |page_name| %>
            <li class="<%= page_name %> <%= "selected" if params[:id] == page_name %>"><%= link_to t("pages.#{page_name}.title"), page_path(page_name) %></li>
          <% end %>
        </ul>
      </nav>
    </header>
    <section class="main">
      <%= yield %>
    </section>
  </div>

</body>
</html>

app/views/pages/contact-us.html.erb
<% title t("pages.contact-us.title") %>

<h1><%= t("pages.contact-us.header") %></h1>

<div class="map">
  <iframe width="960" height="450" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=cs&amp;geocode=&amp;q=Pivovarsk%C3%A1+5,+Praha,+%C4%8Cesk%C3%A1+republika&amp;aq=0&amp;oq=Pivovarska+5&amp;sll=37.0625,-95.677068&amp;sspn=40.409448,86.572266&amp;ie=UTF8&amp;hq=&amp;hnear=Pivovarsk%C3%A1+597%2F5,+150+00+Praha,+%C4%8Cesk%C3%A1+republika&amp;t=m&amp;ll=50.074053,14.408655&amp;spn=0.01928,0.036564&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe>
</div>

<section class="contact-details">
  <ul>
    <li><strong>Телефон:</strong> +420 777-486-548</li>
    <li><strong>Адрес:</strong>  hotel Angelis, Praha 5, ul. Pivovarská 5, st. metra Anděl</li>
    <li><strong>Эл. почта:</strong> <%= mail_to "olvitacompani@gmail.com" %></li>
  </ul>
</section>

app/views/pages/feedback.html.erb
<% title t("pages.feedback.title") %>

<h1><%= t("pages.feedback.header") %></h1>

<%= simple_form_for :feedback, url: send_feedback_path do |f| %>
  <fieldset>
    <%= f.input :message, as: :text, label: false, required: false, autofocus: true %>
    <%= f.input :name, required: false, input_html: { class: "short" } %>
    <%= f.input :phone_or_email, required: false, input_html: { class: "short" } %>
  </fieldset>

  <div class="actions">
    <%= f.submit "Отправить", class: "dark button" %>
  </div>
<% end %>

app/views/pages/publications.html.erb
<% title t("pages.publications.title") %>

<h1><%= t("pages.publications.header") %></h1>
<ul class="publications-list">
  <li><%= link_to "Nechci sex", "http://olvita.wgz.cz/clanky/nechci-sex.html" %></li>
  <li><%= link_to "Práce na sobě", "http://olvita.wgz.cz/clanky/prace-na-sobe.html" %></li>
  <li><%= link_to "Něco o tělesné terapii", "http://olvita.wgz.cz/clanky/neco-o-telesne-terapii.html" %></li>
</ul>

app/views/pages/show.html.erb
<h1>Pages#show</h1>
<p>Find me in app/views/pages/show.html.erb</p>

app/views/pages/trainings.html.erb
<% title t("pages.trainings.title") %>

<article class="trainings">
  <div class="column">
    <p>
      В любое время каждый человек может заглянуть в интернет и получить доступ к фантастическим
      ресурсам человеческой мудрости, но огромный набор полученной информации, , как
      правило ,не меняет жизнь людей, не приносит им успеха или счастья .Информация дает лишь
      повод к размышлениям, но не к действиям. Такую возможность дают только тренинги или
      индивидуальная работа с психологом.
    </p>
    <p>
      Наш проект создавался медленно и кропотливо и появился на свет ровно в тот момент, когда
      полученный опыт был грамотно структурирован и приобрел форму. Это определенная школа
      жизни помещенная в ограниченные временные рамки, которая позволит вам заново открыть для
      себя мир, который умещен в первую очередь в вас, а потом и вокруг вас.
    </p>
  </div>
  <div class="column">
    <p>
      Когда мы делали этот тренинг мы хотели, чтобы он был максимально ясен и понятен каждой
      женщине, чтобы он не только давал ответы на волнующие вопросы и помогал найти решения
      острых проблем ,существующих в мире женщины на данный момент, но и создавал основу для
      нового автономного этапа в ее жизни. Ведь мир без иллюзий может быть и есть намного ярче
      и интереснее Мы не предлагаем готового образца « как правильно «,только женщина может
      почувствовать и выбрать ,какой ей быть и как ей жить. Но мы хотим , чтобы каждая женщина,
      выходя из аудитории, была уверенна в том, что она осознанно сможет решить свои проблемы
      сама ,благодаря тому .что она найдет свое направление в работе и свой ритм движения .
    </p>
  </div>
</article>

<aside class="authors">
  <section class="author">
    <div class="name">
      <%= image_tag "olga_small.jpg" %>
      <h1>Ольга Юрьевна Железнова</h1>
    </div>
    <p>
      Ольга Железнова сама по себе является жемчужиной данного проекта. 
      Как профессионал она посвятила 20 лет жизни работе с пациентами через индивидуальную терапию, 
      но параллельно с этим ее всегда интересовала особая актуальность темы Женщины для современности.
    </p>
  </section>
</aside>

<article class="muse">
  <h1>Проект Муза</h1>
  <h2>Авторская школа женского совершенства</h2>

  <section class="quote">
    <p>
      <span style="margin: -0.7em 0 0 -0.7em;">«</span>
      Вы не можете научить человека чему-либо .чего он уже бы не знал ,вы лишь можете довести то, что он знает ,до его сознания.
      <span style="margin: -0.5em 0 0 0.1em;">»</span>
    </p>
    <small><strong>Галилео Галилей</strong></small>
  </section>

  <div class="clearfix"></div>

  <h2>Мы не претендуем на истину ,но хотим поделитьс я огромным практическим опытом</h2>

  <div class="column">
    <p>Название этого проекта возникло не случайно. Муза в переводе с греческого означает мыслящая.</p>
    <p>
      Каждая женщина по сути своей являться Музой, прежде всего для себя - потом для
      окружающих , :Женщина это неограниченный и мощный источник вдохновения и энергии,
      свежести ,новых идей ,Природа создала ее .быть женственной. И это не только рюши и кружева.
      Это больше ,чем подтянутые формы и грация движений .Эта гармония ,которая идет изнутри.
    </p>
    <p>
      Быть Женщин ой величайший шаг и постоянная работа .Обладать источником силы и энергии , и
      умение грамотно ими управлять -это и есть искусство быть Женщиной .Этому мы и будем учиться
      в школе .женской мудрости и совершенства.
    </p>
    <p>
      Наша школа полезна для женщин, которые имеют проблемы в семейных отношени ях
      и ,для женщин ,которые по разным причинам этих отношений не имеют ,для женщин
      одиноких. которые не могут выбрать себе избранника и для женщин которые хотят остаться
      независимыми. она полезна для всех мыслящих женщин ,которые хотят быть счастливыми
      и понимают ,что единственная возможность осуществить -свою мечту является принятие
      ответственности за свою жизнь и развитие.
    </p>
  </div>

  <div class="column">
    <p>
      Занятия  в школе построены так, что каждый модуль может являться самостоятельным тренингом, 
      но в совокупности они представляют целостную систему обучения и развития женщин.
    </p>
    <p>
      На пути к счастью у каждой женщины есть свои препятствия ,но все они укладываются в
      определенные схемы ,по которым мы будем работать.
    </p>
    <p>
      В этой школе Вы являетесь активными Учителями ,потому что каждая из Вас ,обладающая своим уникальным 
      жизненным опытом  ,передает эту мудрость остальным, восстанавливая целостную картину Мироздания…
    </p>
    <p>
      Для прохождения программы необходима удобная одежда и обувь, настрой на глубинную работу и желание 
      чувствовать себя женщиной.
    </p>
  </div>
</article>

<article class="structure">
  <h1>Все занятия разделены на 3 ступени , которые включают в себя 9 пятичасовых модулей</h1>
  <ol class="modules-list">
    <li>
      <h3>Возвращение к себе</h3>

      <h4>Точка опоры</h4>
      <ul>
        <li>Где эта точка опоры, с которой мы можем перевернуть всю свою жизнь?</li>
        <li>Свобода выбора. Кто ее выбирает или как быть автором свой жизни.</li>
        <li>Расчистка завалов на дороге счастья или что нам мешает на этом пути.</li>
        <li>По каким схемам мы живем. Гласные и негласные договора или рождение вечных должников.</li>
        <li>Быть женщиной по половому признаку это путь или ловушка.</li>
        <li>Домашнее задание.</li>
      </ul>

      <section class="quote">
        <p>
          <span style="margin: -0.7em 0 0 -0.7em;">«</span>
          Бессмысленно продолжать делать тоже самое и ждать других результатов.
          <span style="margin: -0.5em 0 0 0.1em;">»</span>
        </p>
        <small><strong>Альберт Эйнштейн</strong></small>
      </section>

      <h4>Осознанность</h4>
      <ul>
        <li>Корни знаний что такое хорошо и что такое плохо. Пересмотр.</li>
        <li>Личные мифы мужчин и женщин.</li>
        <li>Стратегии, которые мы используем.</li>
        <li>Сдержанность разумная и неразумная.</li>
        <li>Искусство отпускать долги и хвосты.</li>
        <li>Домашнее задание.</li>
      </ul>
    </li>

    <li>
      <h3>Я &mdash; женщина</h3>
    </li>

    <li>
      <h3>Быть женщиной &mdash; осознанный выбор</h3>
    </li>
  </ol>
</article>